// <auto-generated />
namespace Hleb.Classes.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Install : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Install));
        
        string IMigrationMetadata.Id
        {
            get { return "201806121422476_Install"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
